version: '3.9'

name: release-test

networks:
  localnet: {}

services:
  server:
    build:
      context: .
      args:
        - PORT=8080
    pull_policy: build
    image: release-test:latest
    container_name: release-test
    init: true
    restart: unless-stopped
    env_file: .env.docker
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - localnet
    ports:
      - 9000:8080
