name: Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: 18.15.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: 18.15.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: 18.15.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: latest
          path: dist

  release:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    name: Release
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version: 18.15.0
      - uses: actions/download-artifact@v3
        with:
          name: latest
          path: dist
      - run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: |
          RELEASE_ASSET=$(npm pack --silent)
          pnpm dlx release-it --no-npm.publish --github.release --github.assets="${RELEASE_ASSET}" --github.autoGenerate --git.commitMessage='chore: release v${version}' --git.pushArgs=--follow-tags --ci
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
